#!/usr/bin/env bash
# Create or find an existing MR/PR for the published docs branch.
# Reads publish-info.json and repo-info.json from artifacts/<ticket>/.
# Writes mr-info.json with the result.
#
# Usage: bash repo-create-mr.sh <ticket-id> [--dry-run]
#
# Dependencies: python3, curl (for GitLab), gh CLI (for GitHub)
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# --- Argument parsing ---
TICKET=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    -*) echo "ERROR: Unknown option: $1" >&2; exit 1 ;;
    *) TICKET="$1"; shift ;;
  esac
done

if [[ -z "$TICKET" ]]; then
  echo "ERROR: Ticket ID is required." >&2
  echo "Usage: bash repo-create-mr.sh <ticket-id> [--dry-run]" >&2
  exit 1
fi

TICKET_LOWER="$(echo "$TICKET" | tr '[:upper:]' '[:lower:]')"
TICKET_UPPER="$(echo "$TICKET" | tr '[:lower:]' '[:upper:]')"
OUTPUT_DIR="${REPO_ROOT}/artifacts/${TICKET_LOWER}"

# --- Read publish-info.json ---
PUBLISH_INFO="${OUTPUT_DIR}/publish-info.json"

if [[ ! -f "$PUBLISH_INFO" ]]; then
  echo "No publish-info.json found at ${PUBLISH_INFO}. Nothing to do."
  exit 0
fi

eval "$(python3 -c "
import json, sys, shlex
d = json.load(open(sys.argv[1]))
print(f'PUSHED={shlex.quote(str(d.get(\"pushed\", False)).lower())}')
print(f'PUB_BRANCH={shlex.quote(d.get(\"branch\", \"\"))}')
print(f'PUB_PLATFORM={shlex.quote(d.get(\"platform\", \"\"))}')
print(f'PUB_REPO_URL={shlex.quote(d.get(\"repo_url\", \"\"))}')
" "$PUBLISH_INFO")"

if [[ "$PUSHED" != "true" ]]; then
  echo "publish-info.json has pushed=false. Skipping MR/PR creation."
  python3 -c "
import json, sys
print(json.dumps({
    'platform': sys.argv[1],
    'url': None,
    'action': 'skipped',
    'title': None,
    'reason': 'branch not pushed'
}, indent=2))
" "$PUB_PLATFORM" > "${OUTPUT_DIR}/mr-info.json"
  exit 0
fi

# --- Read repo-info.json for additional context ---
REPO_INFO="${OUTPUT_DIR}/repo-info.json"

eval "$(python3 -c "
import json, sys, shlex
d = json.load(open(sys.argv[1]))
print(f'REPO_URL={shlex.quote(d.get(\"repo_url\") or \"\")}')
print(f'DEFAULT_BRANCH={shlex.quote(d.get(\"default_branch\", \"main\"))}')
print(f'PLATFORM={shlex.quote(d.get(\"platform\", \"\"))}')
print(f'BRANCH={shlex.quote(d.get(\"branch\", \"\"))}')
" "$REPO_INFO")"

# --- Build MR/PR title ---
# Try to extract a summary from requirements, fall back to generic title
REQUIREMENTS_FILE="${OUTPUT_DIR}/requirements/requirements.md"
SUMMARY=""
if [[ -f "$REQUIREMENTS_FILE" ]]; then
  SUMMARY="$(python3 -c "
import sys, re
with open(sys.argv[1]) as f:
    for line in f:
        line = line.strip()
        m = re.match(r'^#+\s+(.+)', line)
        if m:
            title = m.group(1)
            # Strip ticket ID prefix if present
            title = re.sub(r'^' + re.escape(sys.argv[2]) + r'\s*[-:]\s*', '', title, flags=re.IGNORECASE)
            if title:
                # Truncate to 80 chars
                print(title[:80])
                break
" "$REQUIREMENTS_FILE" "$TICKET_UPPER" 2>/dev/null || true)"
fi

if [[ -z "$SUMMARY" ]]; then
  SUMMARY="generated documentation"
fi

TITLE="docs(${TICKET_UPPER}): ${SUMMARY}"

# --- Build MR/PR description ---
DESCRIPTION="Documentation generated by the Ambient docs pipeline.

**JIRA ticket:** ${TICKET_UPPER}
**Branch:** ${BRANCH}
**Target:** ${DEFAULT_BRANCH}"

# Append committed files if available
FILES_LIST="$(python3 -c "
import json, sys
d = json.load(open(sys.argv[1]))
files = d.get('files_committed', [])
if files:
    for f in files:
        print(f'- \`{f}\`')
" "$PUBLISH_INFO" 2>/dev/null || true)"

if [[ -n "$FILES_LIST" ]]; then
  DESCRIPTION="${DESCRIPTION}

**Files:**
${FILES_LIST}"
fi

# --- Dry-run output ---
if [[ "$DRY_RUN" == "true" ]]; then
  echo "=== DRY RUN ==="
  echo "Platform: ${PLATFORM}"
  echo "Repo URL: ${REPO_URL}"
  echo "Branch: ${BRANCH}"
  echo "Target: ${DEFAULT_BRANCH}"
  echo "Title: ${TITLE}"
  echo "Description:"
  echo "$DESCRIPTION"
  echo "==============="
  exit 0
fi

# --- Source credentials ---
source ~/.env 2>/dev/null || true

# --- Helper: write mr-info.json ---
write_mr_info() {
  local url="$1"
  local action="$2"
  python3 -c "
import json, sys
print(json.dumps({
    'platform': sys.argv[1],
    'url': sys.argv[2] if sys.argv[2] != 'null' else None,
    'action': sys.argv[3],
    'title': sys.argv[4]
}, indent=2))
" "$PLATFORM" "$url" "$action" "$TITLE" > "${OUTPUT_DIR}/mr-info.json"
  echo "Wrote ${OUTPUT_DIR}/mr-info.json"
}

# --- Platform-specific MR/PR creation ---
if [[ "$PLATFORM" == "gitlab" ]]; then
  # Extract project path from GitLab URL
  # https://gitlab.com/org/repo.git -> org/repo
  PROJECT_PATH="$(echo "$REPO_URL" | sed -E 's|https?://[^/]+/||; s|\.git$||')"
  ENCODED_PATH="$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1], safe=''))" "$PROJECT_PATH")"

  # Determine GitLab host from URL
  GITLAB_HOST="$(echo "$REPO_URL" | sed -E 's|(https?://[^/]+).*|\1|')"

  if [[ -z "${GITLAB_TOKEN:-}" ]]; then
    echo "ERROR: GITLAB_TOKEN not set. Cannot create MR." >&2
    write_mr_info "null" "skipped"
    exit 1
  fi

  # Check for existing MR
  EXISTING_MR="$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
    "${GITLAB_HOST}/api/v4/projects/${ENCODED_PATH}/merge_requests?source_branch=${BRANCH}&state=opened" 2>/dev/null || echo "[]")"

  EXISTING_URL="$(python3 -c "
import json, sys
data = json.loads(sys.argv[1])
if isinstance(data, list) and len(data) > 0:
    print(data[0].get('web_url', ''))
else:
    print('')
" "$EXISTING_MR" 2>/dev/null || echo "")"

  if [[ -n "$EXISTING_URL" ]]; then
    echo "Found existing MR: ${EXISTING_URL}"
    write_mr_info "$EXISTING_URL" "found_existing"
    echo "$EXISTING_URL"
    exit 0
  fi

  # Create new MR
  MR_RESPONSE="$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
    --header "Content-Type: application/json" \
    --data "$(python3 -c "
import json, sys
print(json.dumps({
    'source_branch': sys.argv[1],
    'target_branch': sys.argv[2],
    'title': sys.argv[3],
    'description': sys.argv[4]
}))
" "$BRANCH" "$DEFAULT_BRANCH" "$TITLE" "$DESCRIPTION")" \
    "${GITLAB_HOST}/api/v4/projects/${ENCODED_PATH}/merge_requests" 2>/dev/null || echo "{}")"

  MR_URL="$(python3 -c "
import json, sys
d = json.loads(sys.argv[1])
print(d.get('web_url', ''))
" "$MR_RESPONSE" 2>/dev/null || echo "")"

  if [[ -n "$MR_URL" ]]; then
    echo "Created MR: ${MR_URL}"
    write_mr_info "$MR_URL" "created"
    echo "$MR_URL"
  else
    echo "ERROR: Failed to create MR. Response: ${MR_RESPONSE}" >&2
    write_mr_info "null" "skipped"
    exit 1
  fi

elif [[ "$PLATFORM" == "github" ]]; then
  # Extract owner/repo from GitHub URL
  # https://github.com/owner/repo.git -> owner/repo
  OWNER_REPO="$(echo "$REPO_URL" | sed -E 's|https?://github\.com/||; s|\.git$||')"

  # Check for existing PR
  EXISTING_PR="$(gh pr list --head "$BRANCH" --repo "$OWNER_REPO" --json url --jq '.[0].url' 2>/dev/null || echo "")"

  if [[ -n "$EXISTING_PR" ]]; then
    echo "Found existing PR: ${EXISTING_PR}"
    write_mr_info "$EXISTING_PR" "found_existing"
    echo "$EXISTING_PR"
    exit 0
  fi

  # Create new PR
  PR_URL="$(gh pr create \
    --repo "$OWNER_REPO" \
    --head "$BRANCH" \
    --base "$DEFAULT_BRANCH" \
    --title "$TITLE" \
    --body "$DESCRIPTION" 2>&1)" || {
    echo "ERROR: Failed to create PR: ${PR_URL}" >&2
    write_mr_info "null" "skipped"
    exit 1
  }

  echo "Created PR: ${PR_URL}"
  write_mr_info "$PR_URL" "created"
  echo "$PR_URL"

else
  echo "ERROR: Unknown platform '${PLATFORM}'." >&2
  write_mr_info "null" "skipped"
  exit 1
fi
